# ESPHome configuration file for teleinfokit module https://342apps.net/module-teleinfokit/

esphome:
  name: teleinfokit_esphome
  platform: ESP8266
  board: esp01_1m


# update all CHANGE_ME values and remove # in front of the value

wifi:
  ssid: #"CHANGE_ME"  # update to you wifi SSID
  password: #"CHANGE_ME"  # update to your wifi password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Teleinfokit Esphome"
    password: #"CHANGE_ME"   # update to a random password

captive_portal:

# Enable logging
logger:     
  baud_rate: 0   # disable logging via UART, help to avoid numerous crash with ESP_LOGD
  level: INFO   # INFO for less log, put DEBUG to view all the linky's "étiquettes" received  in the logs
  esp8266_store_log_strings_in_flash: False     #  :doc:`recommanded for ESP8266 </components/sensor/custom>`

# Enable Home Assistant API
api:
  password: #"CHANGE_ME"   # update to a random password

ota:
  password: #"CHANGE_ME"   # update to a random password


uart:
  id: uart_bus
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 1200
  parity: EVEN
  data_bits: 7

sensor:
  - platform: teleinfo
    tags:
     - tag_name: "HCHC"
       sensor:
        name: "hchc"
        id: hchc
        unit_of_measurement: "Wh"
        icon: mdi:flash
     - tag_name: "HCHP"
       sensor:
        id: hchp
        name: "hchp"
        unit_of_measurement: "Wh"
        icon: mdi:flash
     - tag_name: "PAPP"
       sensor:
        id: papp
        name: "papp"
        unit_of_measurement: "VA"
        icon: mdi:flash
    update_interval: 30s
    historical_mode: true

i2c:
  sda: GPIO0
  scl: GPIO2

font:
  - file: "arial.ttf"
    id: arial_font
    size: 16

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    id: oled
    rotation: 180°
    address: 0x3C
    pages:
      - id: page1
        lambda: |-
          it.printf(0, 0, id(arial_font), "Conso: %.0f VA", id(papp).state);
      - id: page2
        lambda: |-
          it.printf(0, 0, id(arial_font), "HP: %.0f", id(hchp).state);
      - id: page3
        lambda: |-
          it.printf(0, 0, id(arial_font), "HC: %.0f", id(hchc).state);

interval:
  - interval: 5s
    then:
      - display.page.show_next: oled
      - component.update: oled
